# Generated by Django 2.2 on 2020-02-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=90)),
                ('alias', models.CharField(max_length=45)),
                ('pw', models.CharField(max_length=90)),
                ('birthday', models.DateTimeField()),
                ('level', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=15)),
                ('description', models.CharField(default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
